// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQVOPOOOqQPO'#C^OOOO'#Cd'#CdOOOO'#Ck'#CkOOOO'#Cf'#CfQVOPOOOvQQO'#C`O!OQQO,58xOOOO-E6d-E6dO!TQPO'#CgO!YQQO,58zOOOO1G.d1G.dOOQO,59R,59ROOQO-E6e-E6e",
  stateData: "!k~O^OS~ORPOTQOVROXQO^QO`QOaQObQO~O`UO~OTXOUSX~OUZO~O`[O~OTXOUSa~ORUV^`TX^~",
  goto: "x`PPaPePPPaPhnPPPtTROTRVPQTORWTQYUR]YTSOT",
  nodeNames: "⚠ Template Variable {{ Path . }} EscapedBrace Text TextChunk",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "%a~RgOX!jXY#kYZ#kZ]!j]^#k^p!jpq#kq!O!j!O!P#|!P!c!j!c!}$R!}#O!j#O#P$d#P#R!j#R#S$R#S#T!j#T#o$R#o#p$u#p#q!j#q#r%S#r;'S!j;'S;=`#e<%lO!j~!o[X~OX!jZ]!j^p!jq!O!j!P!c!j!}#O!j#P#R!j#S#T!j#p#q!j#r;'S!j;'S;=`#e<%lO!j~#hP;=`<%l!j~#pS^~XY#kYZ#k]^#kpq#k~$ROT~~$WS`~!Q![$R!c!}$R#R#S$R#T#o$R~$gP#o#p$j~$mP#o#p$p~$uOV~~$zPb~#o#p$}~%SOR~R%XPaP#q#r%[Q%aOUQ",
  tokenizers: [0, 1],
  topRules: {"Template":[0,1]},
  tokenPrec: 64
})
